#!/usr/bin/env bash

# Log a message with format: [timestamp][log level] context: message
#   Where context is "main" if this function is called from a script, or the name of the function calling this logging function
#
# Parameters
#   $1: log_level, can be either a number between 0 and 3 (0 debug...3 error), or the name of the level
#                   name of the logging levels: debug, info, warning (or warn), error (or err)
#   $2: message to print
#   $3: number of functions to ignore from the stack function. Used if the logging function is called from a "util" function,
#       which is not the principal function where we want our log to come from.
function shlog()
{
    local log_level=$1
    local message="$2"
    local nb_func_ignore=${3:-0}

    # variables used for logging

    # Colors
    local _shlog_esc_char="\e"
    local _shlog_color_red="${_shlog_esc_char}[31m"
    local _shlog_color_green="${_shlog_esc_char}[32m"
    local _shlog_color_yellow="${_shlog_esc_char}[33m"
    local _shlog_color_blue="${_shlog_esc_char}[34m"
    local _shlog_color_reset="${_shlog_esc_char}[0m"
    local _shlog_bold="${_shlog_esc_char}[1m"

    # Logging levels and their associated colors and names
    local _shlog_level_debug=0
    local _shlog_level_info=1
    local _shlog_level_warning=2
    local _shlog_level_error=3

    local -A _shlog_colors=(
        [$_shlog_level_debug]="${_shlog_color_blue}"
        [$_shlog_level_info]="${_shlog_color_green}"
        [$_shlog_level_warning]="${_shlog_color_yellow}"
        [$_shlog_level_error]="${_shlog_color_red}"
    )

    local -A _shlog_levels=(
        [$_shlog_level_debug]="DEBUG"
        [$_shlog_level_info]="INFO"
        [$_shlog_level_warning]="WARNING"
        [$_shlog_level_error]="ERROR"
    )

    local -A _shlog_param=(
        [debug]=$_shlog_level_debug
        [info]=$_shlog_level_info
        [warning]=$_shlog_level_warning
        [warn]=$_shlog_level_warning
        [error]=$_shlog_level_error
        [err]=$_shlog_level_error
    )

    # Variables
    # minimum level for each log message to be logged, by default 1 (INFO).
    local shlog_level=${SHLOG_LEVEL:-1}

    # log file where to save the logged messages (in addition to displaying them in terminal)
    # Default: no log file
    local shlog_file=${SHLOG_FILE:-}

    # FUNCNAME only works under bash
    # if this logging function is called from a shlog_(debug|info|warning|error) function,
    # then the calling function is two functions away in the calling stack
    # else the calling function is one function away in the calling stack
    if [[ "${FUNCNAME[*]}" =~ "shlog_" ]]; then
        local context="${FUNCNAME[(( 2 + $nb_func_ignore))]}"
    else
        local context="${FUNCNAME[(( 1 + $nb_func_ignore ))]}"
    fi

    # convert log_level to the corresponding integer if a string was passed
    if [[ "${#log_level}" -ne 1 ]]; then
        log_level="${_shlog_param[$log_level]}"

        # if this logging level does not exist, then log an ERROR explaining the problem
        if [[ -z "$log_level" ]]; then
            message="Bad parameter to shlog: \"$1\" is not an existing log level. Log message: \"$message\"."
            log_level=3
        fi
    fi

    # only display logs that have a higher/equal level than/to shlog_level
    if [[ ${log_level} -lt ${shlog_level} ]]; then
        return
    fi

    local level_name="${_shlog_levels[$log_level]}"
    # all log level (names) have the same size for a better display
    while [[ ${#level_name} -lt 7 ]]; do
            level_name="${level_name} "
    done
    local color="${_shlog_colors[$log_level]}"

    local timestamp
    timestamp="$(date -Is)"
    local log_string="[${timestamp}][${color}${level_name}${_shlog_color_reset}]"
    if [[ -n "$context" ]]; then
        log_string="$log_string ${_shlog_bold}${context}${_shlog_color_reset}:"
    fi
    log_string="$log_string ${message}"
    if [[ -z "${shlog_file}" ]]; then
        builtin echo -e "${log_string}"
    else
        builtin echo -e "${log_string}" | tee -a "${shlog_file}"
    fi
}

# Log a message using shlog, with log level debug
function shlog_debug()
{
    shlog debug "$@"
}

# Log a message using shlog, with log level info
function shlog_info()
{
    shlog info "$@"
}

# Log a message using shlog, with log level warning
function shlog_warning()
{
    shlog warning "$@"
}

# Log a message using shlog, with log level error
function shlog_error()
{
    shlog error "$@"
}

function shlog_command() {
    if [[ "$#" -lt 1 ]]; then
        builtin echo "Usage: shlog_command [--quiet|--redirects REDIRECTS] COMMAND"
    fi

    local quiet=0
    local redirect=0
    local redirects=""
    if [[ "$1" == "--quiet" || "$1" == "-q" ]]; then
        quiet=1
        builtin shift
    fi
    if [[ "$1" == "--redirects" || "$1" == "-r" ]]; then
        redirect=1
        builtin shift
        redirects="$1"
        builtin shift
    fi
    local cmd=("$@")

    shlog debug "Running command: '${cmd[*]}'"
    
    local t_start="$EPOCHREALTIME"
    if [[ "$quiet" -eq 1 ]]; then
        "${cmd[@]}" &> /dev/null
    elif [[ "$redirect" -eq 1 ]]; then
        builtin eval "${cmd[@]}" $redirects
    else
        "${cmd[@]}"
    fi
    local ret="$?"
    local t_end="$EPOCHREALTIME"

    if [[ "$ret" -eq 0 ]]; then
        shlog info "Command '${cmd[*]}' succeeded in $((t_end - t_start))s"
    else
        shlog error "Command '${cmd[*]}' failed in $((t_end - t_start))s"
    fi
}
